version: "3.9"
services:
  db:
    image: postgres:13    
    restart: always
    env_file:
      - ./backend/.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
  backend:
      image: semenovaliza/movie_backend:v1.08.2025
      expose:
        - "8000" 
      volumes:      
        - static_volume:/opt/backend/static
      env_file:
        - ./backend/.env
      depends_on:
        - db
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/nginx/conf.d:/etc/nginx/conf.d
      - ./backend/data:/backend/data/      
      - static_volume:/opt/backend/static
    depends_on:
      - backend
    ports:
      - "8000:80"

volumes:
  postgres_data:
  static_volume: